### ISSUE TITLE
500 error displaying event imported from Facebook

### ISSUE THREAD

**Issue by jhelwig** [pdxactivist/pdxactivist#1]
```
I, [2017-01-24T04:27:24.673695 #19362]  INFO -- : Started GET "/events/2" for 75.164.151.79 at 2017-01-24 04:27:24 +0000
I, [2017-01-24T04:27:24.675273 #19362]  INFO -- : Processing by Calagator::EventsController#show as HTML
I, [2017-01-24T04:27:24.675316 #19362]  INFO -- :   Parameters: {"id"=>"2"}
D, [2017-01-24T04:27:24.676749 #19362] DEBUG -- :   Calagator::Event Load (0.6ms)  SELECT  `events`.* FROM `events` WHERE `events`.`id` = 2 LIMIT 1
I, [2017-01-24T04:27:24.681784 #19362]  INFO -- :   Rendered vendor/bundle/bundler/gems/calagator-d9cc04b25fca/app/views/calagator/events/_hcal.html.erb (2.7ms)
D, [2017-01-24T04:27:24.683628 #19362] DEBUG -- :   Calagator::Source Load (0.5ms)  SELECT  `sources`.* FROM `sources` WHERE `sources`.`id` = 2 LIMIT 1
D, [2017-01-24T04:27:24.688541 #19362] DEBUG -- :   ActsAsTaggableOn::Tag Load (0.6ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 2 AND `taggings`.`t
I, [2017-01-24T04:27:24.690089 #19362]  INFO -- :   Rendered vendor/bundle/bundler/gems/calagator-d9cc04b25fca/app/views/calagator/events/_item.html.erb (5.8ms)
I, [2017-01-24T04:27:24.690162 #19362]  INFO -- :   Rendered vendor/bundle/bundler/gems/calagator-d9cc04b25fca/app/views/calagator/events/show.html.erb within layouts/calagator/application (12.6ms)
I, [2017-01-24T04:27:24.690335 #19362]  INFO -- : Completed 500 Internal Server Error in 15ms (ActiveRecord: 1.6ms)
F, [2017-01-24T04:27:24.692373 #19362] FATAL -- :
ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    113:     <% unless event.tags.blank? -%>
    114:     <h3>Tags</h3>
    115:     <div class="tags">
    116:         <%= tag_links_for event %>
    117:     </div>
    118:     <% end %>
    119:   </div>
  vendor/bundle/bundler/gems/calagator-d9cc04b25fca/app/helpers/calagator/tags_helper.rb:50:in `exists?'
  vendor/bundle/bundler/gems/calagator-d9cc04b25fca/app/helpers/calagator/tags_helper.rb:19:in `text'
  vendor/bundle/bundler/gems/calagator-d9cc04b25fca/app/helpers/calagator/tags_helper.rb:12:in `render'
  vendor/bundle/bundler/gems/calagator-d9cc04b25fca/app/helpers/calagator/tags_helper.rb:6:in `block in tag_links_for'
  vendor/bundle/bundler/gems/calagator-d9cc04b25fca/app/helpers/calagator/tags_helper.rb:5:in `map'
  vendor/bundle/bundler/gems/calagator-d9cc04b25fca/app/helpers/calagator/tags_helper.rb:5:in `tag_links_for'
  vendor/bundle/bundler/gems/calagator-d9cc04b25fca/app/views/calagator/events/_item.html.erb:116:in `_vendor_bundle_bundler_gems_calagator_d_cc__b__fca_app_views_calagator_events__item_html_erb___1777815802081646277_4730625685
...
```

**Comment by jhelwig** [comment]
Looks like an asset compilation issue, since we're blowing up at https://github.com/calagator/calagator/blob/master/app/helpers/calagator/tags_helper.rb#L50

**Comment by jhelwig** [comment]
![Missing tag image](https://cloud.githubusercontent.com/assets/14557/22234934/e4f76b60-e1b0-11e6-8a57-73f1d567e463.png)
Image still isn't working for the Facebook tag, because we're ending up with a `background-` property in the CSS, instead of `background-image`.
![malformed CSS](https://cloud.githubusercontent.com/assets/14557/22234927/cfb81bd2-e1b0-11e6-83ae-6c49b62c90aa.png)
